spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USERSERVICE
              uri: lb://USERSERVICE
              predicates:
                - Path=/users/**
            - id: DEPARTMENTSERVICE
              uri: lb://DEPARTMENTSERVICE
              predicates:
                - Path=/departments/**
  config:
    import: configserver:http://localhost:9296
server:
  port: 9191

#Using config server for eureka client configuration below ->
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instances:
#    hostname: localhost
