spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENTSERVICE
          uri: lb://DEPARTMENTSERVICE
          predicates:
            - Path=/departments/**

server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instances:
    hostname: localhost
