spring:
  application:
    name: UserService
  config:
    import: configserver:http://localhost:9296


server:
  port: 9002

#Using config server for eureka client configuration below ->
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instances:
#    hostname: localhost
